//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""MainControls"",
            ""id"": ""f84bda52-e4fc-4e43-a269-9eb07fffe283"",
            ""actions"": [
                {
                    ""name"": ""ControlAxis"",
                    ""type"": ""Value"",
                    ""id"": ""c01cda30-afae-4505-b2c9-4dedc216d4d1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""b40a3041-a96f-4192-a2f6-2464c1cb5c3d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""4c10bfe5-0f32-4950-be78-78878a94c4d0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartButton"",
                    ""type"": ""Button"",
                    ""id"": ""d6f1774e-2a07-47f9-a6ae-f6a0070ff5a4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AffirmButton"",
                    ""type"": ""Button"",
                    ""id"": ""6b46fe2c-a342-457e-b69b-91351414669c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RejectButton"",
                    ""type"": ""Button"",
                    ""id"": ""5680fe2b-4c15-48ce-92dc-000c1ea7154b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuButton1"",
                    ""type"": ""Button"",
                    ""id"": ""84b1ce27-e6b0-45fe-8c37-56f643a4c610"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuButton2"",
                    ""type"": ""Button"",
                    ""id"": ""07485d20-4a93-468f-a448-345ab7ad86a2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""833f1c77-cb84-44fd-b8e3-c3b277ee4c7f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pointer"",
                    ""type"": ""Value"",
                    ""id"": ""9584aea4-909e-4d3f-ae64-56554acf123f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""6c4f7f97-e178-44ea-bf14-902752b7d330"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector (Keyboard)"",
                    ""id"": ""c7de3d37-8d65-49cb-9695-1b8ac27be2da"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControlAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""83b94456-4fcf-4278-b5aa-f4619ad8de5b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""ControlAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c27d0a05-096b-4535-ace8-cf632daf2575"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""ControlAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1c6c2a0f-374f-4c59-b0c4-17b4cd5ef9e2"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""ControlAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b42b024f-1376-4445-bb02-851bf40601c3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""ControlAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ffac3cb9-cedc-4612-a044-77923f61a30f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""ControlAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bb48467f-d2df-40c1-88d8-19fcd688e1ee"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""ControlAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""e7eff52d-4c28-4ff9-9526-e18525c7cb96"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""ControlAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""d31f6fa9-0092-49bf-b088-eecc75220449"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""ControlAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""96ff58ef-9f1c-49e0-bdbc-1d7d36082373"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""MenuButton2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14d4b5a1-4575-4243-88dd-529a5fac5b29"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MenuButton2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5228eb5d-caf3-46a0-bdb8-51ca2585b186"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""MenuButton1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""253bd9c6-d1fa-4fba-888b-0a8620f14f36"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""MenuButton1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51e40533-f2cf-4b64-8424-34b7431ecb8c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""RejectButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9bf3e83-f5c0-4b23-8173-41661b69c327"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""RejectButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbfe4a19-8fa8-47c9-9683-1899fa42d5f5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""RejectButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5085c927-f0f0-406f-8bce-c38decc2c942"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""StartButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a849539-0a38-4c72-880a-6475fb781966"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""StartButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0be6348-cff9-41ee-b55b-2114db0eca71"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""StartButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e139aa4-c66d-4117-825c-bb5dfa99586c"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""SecondaryTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b6416b9-01dc-4d6e-ad2d-a97b81f325fc"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""SecondaryTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bd497f6-48d6-4da8-9438-78a1a8364421"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""SecondaryTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bfa9fe3-29ac-4343-9f57-c1beeb33764b"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""PrimaryTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c3be614-364a-4c56-b4ae-a64651df1e0f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""PrimaryTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""316f9648-8136-4327-9c20-840976565682"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""PrimaryTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""425863d7-7466-414d-af12-e01c1b5a02c8"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""AffirmButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67246d6f-3903-45b9-a86a-977ba878af92"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AffirmButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce994ed7-97f3-4ab8-89dd-3d9437099aef"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""AffirmButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78a3340c-68d1-4365-ba13-fa12d9c72597"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""ControlAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83a4abac-d56f-46ac-819f-65d31282a575"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""ControlAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86e9fe5b-df6a-47dd-b943-2a61db875506"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55b6817c-51d9-4a4e-a30f-f29ff12f1a5d"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""Pointer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d498bf60-7cb4-4107-926f-fb428db91ab5"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debug"",
            ""id"": ""0c2f11ea-dfea-4b3a-9af7-9142c9d672db"",
            ""actions"": [
                {
                    ""name"": ""Debug0"",
                    ""type"": ""Button"",
                    ""id"": ""eb475a5a-a25b-493a-ae25-5a745d8b37b0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug1"",
                    ""type"": ""Button"",
                    ""id"": ""590c01e1-6648-4f01-b8c0-8eb0c9011555"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug2"",
                    ""type"": ""Button"",
                    ""id"": ""5d1e6575-83bf-4bf4-b538-1feb2a697c3d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""061cfe0c-9406-47e2-8d41-63a8378eb860"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""Debug0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""[\\ + ']"",
                    ""id"": ""fd0c4f57-ada7-456a-8922-f9e74fc15b35"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug0"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""c133a562-7726-4460-8b0a-7f700bc3c9cb"",
                    ""path"": ""<Keyboard>/backslash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""Debug0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""dcf103af-96c9-406e-9657-78e4a8e647f1"",
                    ""path"": ""<Keyboard>/quote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""Debug0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""[Start + Select]"",
                    ""id"": ""f4005d7e-c797-40cc-80be-734051d4986b"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug0"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""ca688e16-2207-4d20-9684-d263efe1a890"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Debug0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""045645d9-90c7-409a-bd07-767b89320e19"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Debug0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8d743e1b-e388-4f04-b7ba-677353d1eb74"",
                    ""path"": ""<Keyboard>/f9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""Debug1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""[Start + R3]"",
                    ""id"": ""515808ed-a9a1-4e1a-86d0-a9a3ac4a5a9e"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""2d74c8a4-6b8f-44ff-8478-7a5be3834f3b"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Debug1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""a266b0ae-ccb9-4bb5-af48-df7be47f0f8e"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Debug1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""556829e5-102c-4e22-ab30-6d1adab8ed03"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardMouse"",
                    ""action"": ""Debug2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""[Select + L3]"",
                    ""id"": ""8853fe79-3b79-43a0-bd53-7a81f3ef00d6"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""e824a8d9-ec6f-4ea6-840c-962dad7952a4"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Debug2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""e5ef21f5-572c-49dc-84ab-878cf722a358"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Debug2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardMouse"",
            ""bindingGroup"": ""KeyboardMouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // MainControls
        m_MainControls = asset.FindActionMap("MainControls", throwIfNotFound: true);
        m_MainControls_ControlAxis = m_MainControls.FindAction("ControlAxis", throwIfNotFound: true);
        m_MainControls_PrimaryTrigger = m_MainControls.FindAction("PrimaryTrigger", throwIfNotFound: true);
        m_MainControls_SecondaryTrigger = m_MainControls.FindAction("SecondaryTrigger", throwIfNotFound: true);
        m_MainControls_StartButton = m_MainControls.FindAction("StartButton", throwIfNotFound: true);
        m_MainControls_AffirmButton = m_MainControls.FindAction("AffirmButton", throwIfNotFound: true);
        m_MainControls_RejectButton = m_MainControls.FindAction("RejectButton", throwIfNotFound: true);
        m_MainControls_MenuButton1 = m_MainControls.FindAction("MenuButton1", throwIfNotFound: true);
        m_MainControls_MenuButton2 = m_MainControls.FindAction("MenuButton2", throwIfNotFound: true);
        m_MainControls_Click = m_MainControls.FindAction("Click", throwIfNotFound: true);
        m_MainControls_Pointer = m_MainControls.FindAction("Pointer", throwIfNotFound: true);
        m_MainControls_Scroll = m_MainControls.FindAction("Scroll", throwIfNotFound: true);
        // Debug
        m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
        m_Debug_Debug0 = m_Debug.FindAction("Debug0", throwIfNotFound: true);
        m_Debug_Debug1 = m_Debug.FindAction("Debug1", throwIfNotFound: true);
        m_Debug_Debug2 = m_Debug.FindAction("Debug2", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_MainControls.enabled, "This will cause a leak and performance issues, PlayerControls.MainControls.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Debug.enabled, "This will cause a leak and performance issues, PlayerControls.Debug.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainControls
    private readonly InputActionMap m_MainControls;
    private List<IMainControlsActions> m_MainControlsActionsCallbackInterfaces = new List<IMainControlsActions>();
    private readonly InputAction m_MainControls_ControlAxis;
    private readonly InputAction m_MainControls_PrimaryTrigger;
    private readonly InputAction m_MainControls_SecondaryTrigger;
    private readonly InputAction m_MainControls_StartButton;
    private readonly InputAction m_MainControls_AffirmButton;
    private readonly InputAction m_MainControls_RejectButton;
    private readonly InputAction m_MainControls_MenuButton1;
    private readonly InputAction m_MainControls_MenuButton2;
    private readonly InputAction m_MainControls_Click;
    private readonly InputAction m_MainControls_Pointer;
    private readonly InputAction m_MainControls_Scroll;
    public struct MainControlsActions
    {
        private @PlayerControls m_Wrapper;
        public MainControlsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ControlAxis => m_Wrapper.m_MainControls_ControlAxis;
        public InputAction @PrimaryTrigger => m_Wrapper.m_MainControls_PrimaryTrigger;
        public InputAction @SecondaryTrigger => m_Wrapper.m_MainControls_SecondaryTrigger;
        public InputAction @StartButton => m_Wrapper.m_MainControls_StartButton;
        public InputAction @AffirmButton => m_Wrapper.m_MainControls_AffirmButton;
        public InputAction @RejectButton => m_Wrapper.m_MainControls_RejectButton;
        public InputAction @MenuButton1 => m_Wrapper.m_MainControls_MenuButton1;
        public InputAction @MenuButton2 => m_Wrapper.m_MainControls_MenuButton2;
        public InputAction @Click => m_Wrapper.m_MainControls_Click;
        public InputAction @Pointer => m_Wrapper.m_MainControls_Pointer;
        public InputAction @Scroll => m_Wrapper.m_MainControls_Scroll;
        public InputActionMap Get() { return m_Wrapper.m_MainControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainControlsActions set) { return set.Get(); }
        public void AddCallbacks(IMainControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_MainControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainControlsActionsCallbackInterfaces.Add(instance);
            @ControlAxis.started += instance.OnControlAxis;
            @ControlAxis.performed += instance.OnControlAxis;
            @ControlAxis.canceled += instance.OnControlAxis;
            @PrimaryTrigger.started += instance.OnPrimaryTrigger;
            @PrimaryTrigger.performed += instance.OnPrimaryTrigger;
            @PrimaryTrigger.canceled += instance.OnPrimaryTrigger;
            @SecondaryTrigger.started += instance.OnSecondaryTrigger;
            @SecondaryTrigger.performed += instance.OnSecondaryTrigger;
            @SecondaryTrigger.canceled += instance.OnSecondaryTrigger;
            @StartButton.started += instance.OnStartButton;
            @StartButton.performed += instance.OnStartButton;
            @StartButton.canceled += instance.OnStartButton;
            @AffirmButton.started += instance.OnAffirmButton;
            @AffirmButton.performed += instance.OnAffirmButton;
            @AffirmButton.canceled += instance.OnAffirmButton;
            @RejectButton.started += instance.OnRejectButton;
            @RejectButton.performed += instance.OnRejectButton;
            @RejectButton.canceled += instance.OnRejectButton;
            @MenuButton1.started += instance.OnMenuButton1;
            @MenuButton1.performed += instance.OnMenuButton1;
            @MenuButton1.canceled += instance.OnMenuButton1;
            @MenuButton2.started += instance.OnMenuButton2;
            @MenuButton2.performed += instance.OnMenuButton2;
            @MenuButton2.canceled += instance.OnMenuButton2;
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @Pointer.started += instance.OnPointer;
            @Pointer.performed += instance.OnPointer;
            @Pointer.canceled += instance.OnPointer;
            @Scroll.started += instance.OnScroll;
            @Scroll.performed += instance.OnScroll;
            @Scroll.canceled += instance.OnScroll;
        }

        private void UnregisterCallbacks(IMainControlsActions instance)
        {
            @ControlAxis.started -= instance.OnControlAxis;
            @ControlAxis.performed -= instance.OnControlAxis;
            @ControlAxis.canceled -= instance.OnControlAxis;
            @PrimaryTrigger.started -= instance.OnPrimaryTrigger;
            @PrimaryTrigger.performed -= instance.OnPrimaryTrigger;
            @PrimaryTrigger.canceled -= instance.OnPrimaryTrigger;
            @SecondaryTrigger.started -= instance.OnSecondaryTrigger;
            @SecondaryTrigger.performed -= instance.OnSecondaryTrigger;
            @SecondaryTrigger.canceled -= instance.OnSecondaryTrigger;
            @StartButton.started -= instance.OnStartButton;
            @StartButton.performed -= instance.OnStartButton;
            @StartButton.canceled -= instance.OnStartButton;
            @AffirmButton.started -= instance.OnAffirmButton;
            @AffirmButton.performed -= instance.OnAffirmButton;
            @AffirmButton.canceled -= instance.OnAffirmButton;
            @RejectButton.started -= instance.OnRejectButton;
            @RejectButton.performed -= instance.OnRejectButton;
            @RejectButton.canceled -= instance.OnRejectButton;
            @MenuButton1.started -= instance.OnMenuButton1;
            @MenuButton1.performed -= instance.OnMenuButton1;
            @MenuButton1.canceled -= instance.OnMenuButton1;
            @MenuButton2.started -= instance.OnMenuButton2;
            @MenuButton2.performed -= instance.OnMenuButton2;
            @MenuButton2.canceled -= instance.OnMenuButton2;
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @Pointer.started -= instance.OnPointer;
            @Pointer.performed -= instance.OnPointer;
            @Pointer.canceled -= instance.OnPointer;
            @Scroll.started -= instance.OnScroll;
            @Scroll.performed -= instance.OnScroll;
            @Scroll.canceled -= instance.OnScroll;
        }

        public void RemoveCallbacks(IMainControlsActions instance)
        {
            if (m_Wrapper.m_MainControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_MainControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainControlsActions @MainControls => new MainControlsActions(this);

    // Debug
    private readonly InputActionMap m_Debug;
    private List<IDebugActions> m_DebugActionsCallbackInterfaces = new List<IDebugActions>();
    private readonly InputAction m_Debug_Debug0;
    private readonly InputAction m_Debug_Debug1;
    private readonly InputAction m_Debug_Debug2;
    public struct DebugActions
    {
        private @PlayerControls m_Wrapper;
        public DebugActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Debug0 => m_Wrapper.m_Debug_Debug0;
        public InputAction @Debug1 => m_Wrapper.m_Debug_Debug1;
        public InputAction @Debug2 => m_Wrapper.m_Debug_Debug2;
        public InputActionMap Get() { return m_Wrapper.m_Debug; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
        public void AddCallbacks(IDebugActions instance)
        {
            if (instance == null || m_Wrapper.m_DebugActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DebugActionsCallbackInterfaces.Add(instance);
            @Debug0.started += instance.OnDebug0;
            @Debug0.performed += instance.OnDebug0;
            @Debug0.canceled += instance.OnDebug0;
            @Debug1.started += instance.OnDebug1;
            @Debug1.performed += instance.OnDebug1;
            @Debug1.canceled += instance.OnDebug1;
            @Debug2.started += instance.OnDebug2;
            @Debug2.performed += instance.OnDebug2;
            @Debug2.canceled += instance.OnDebug2;
        }

        private void UnregisterCallbacks(IDebugActions instance)
        {
            @Debug0.started -= instance.OnDebug0;
            @Debug0.performed -= instance.OnDebug0;
            @Debug0.canceled -= instance.OnDebug0;
            @Debug1.started -= instance.OnDebug1;
            @Debug1.performed -= instance.OnDebug1;
            @Debug1.canceled -= instance.OnDebug1;
            @Debug2.started -= instance.OnDebug2;
            @Debug2.performed -= instance.OnDebug2;
            @Debug2.canceled -= instance.OnDebug2;
        }

        public void RemoveCallbacks(IDebugActions instance)
        {
            if (m_Wrapper.m_DebugActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDebugActions instance)
        {
            foreach (var item in m_Wrapper.m_DebugActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DebugActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DebugActions @Debug => new DebugActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("KeyboardMouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IMainControlsActions
    {
        void OnControlAxis(InputAction.CallbackContext context);
        void OnPrimaryTrigger(InputAction.CallbackContext context);
        void OnSecondaryTrigger(InputAction.CallbackContext context);
        void OnStartButton(InputAction.CallbackContext context);
        void OnAffirmButton(InputAction.CallbackContext context);
        void OnRejectButton(InputAction.CallbackContext context);
        void OnMenuButton1(InputAction.CallbackContext context);
        void OnMenuButton2(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnPointer(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
    }
    public interface IDebugActions
    {
        void OnDebug0(InputAction.CallbackContext context);
        void OnDebug1(InputAction.CallbackContext context);
        void OnDebug2(InputAction.CallbackContext context);
    }
}
